/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type DomainPurchase struct {
	Consent *Consent `json:"consent"`
	ContactAdmin *Contact `json:"contactAdmin,omitempty"`
	ContactBilling *Contact `json:"contactBilling,omitempty"`
	ContactRegistrant *Contact `json:"contactRegistrant,omitempty"`
	ContactTech *Contact `json:"contactTech,omitempty"`
	// For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
	Domain string `json:"domain"`
	NameServers []string `json:"nameServers,omitempty"`
	Period int32 `json:"period,omitempty"`
	Privacy bool `json:"privacy,omitempty"`
	RenewAuto bool `json:"renewAuto,omitempty"`
}
