/*
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package godaddy

import (
	"encoding/json"
)

// RealNameValidation struct for RealNameValidation
type RealNameValidation struct {
	Status *string `json:"status,omitempty"`
}

// NewRealNameValidation instantiates a new RealNameValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealNameValidation() *RealNameValidation {
	this := RealNameValidation{}
	return &this
}

// NewRealNameValidationWithDefaults instantiates a new RealNameValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealNameValidationWithDefaults() *RealNameValidation {
	this := RealNameValidation{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RealNameValidation) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealNameValidation) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RealNameValidation) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *RealNameValidation) SetStatus(v string) {
	o.Status = &v
}

func (o RealNameValidation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableRealNameValidation struct {
	value *RealNameValidation
	isSet bool
}

func (v NullableRealNameValidation) Get() *RealNameValidation {
	return v.value
}

func (v *NullableRealNameValidation) Set(val *RealNameValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableRealNameValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableRealNameValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealNameValidation(val *RealNameValidation) *NullableRealNameValidation {
	return &NullableRealNameValidation{value: val, isSet: true}
}

func (v NullableRealNameValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealNameValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


