/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type VerificationDomainName struct {
	// Status of the domain name verification
	Status string `json:"status"`
}
