/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type PrivacyPurchase struct {
	// Specify agreement `DNPA`.  Required agreements can be retrieved via the GET ./domains/agreements endpoint
	Consent *Consent `json:"consent"`
}
