/*
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package godaddy

import (
	"encoding/json"
)

// DomainTransferIn struct for DomainTransferIn
type DomainTransferIn struct {
	// Authorization code from registrar for transferring a domain
	AuthCode string `json:"authCode"`
	Consent Consent `json:"consent"`
	// Can be more than 1 but no more than 10 years total including current registration length
	Period *int32 `json:"period,omitempty"`
	// Whether or not privacy has been requested
	Privacy *bool `json:"privacy,omitempty"`
	// Whether or not the domain should be configured to automatically renew
	RenewAuto *bool `json:"renewAuto,omitempty"`
	ContactAdmin *Contact `json:"contactAdmin,omitempty"`
	ContactBilling *Contact `json:"contactBilling,omitempty"`
	ContactRegistrant *Contact `json:"contactRegistrant,omitempty"`
	ContactTech *Contact `json:"contactTech,omitempty"`
}

// NewDomainTransferIn instantiates a new DomainTransferIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainTransferIn(authCode string, consent Consent, ) *DomainTransferIn {
	this := DomainTransferIn{}
	this.AuthCode = authCode
	this.Consent = consent
	var privacy bool = false
	this.Privacy = &privacy
	var renewAuto bool = true
	this.RenewAuto = &renewAuto
	return &this
}

// NewDomainTransferInWithDefaults instantiates a new DomainTransferIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainTransferInWithDefaults() *DomainTransferIn {
	this := DomainTransferIn{}
	var privacy bool = false
	this.Privacy = &privacy
	var renewAuto bool = true
	this.RenewAuto = &renewAuto
	return &this
}

// GetAuthCode returns the AuthCode field value
func (o *DomainTransferIn) GetAuthCode() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AuthCode
}

// GetAuthCodeOk returns a tuple with the AuthCode field value
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetAuthCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AuthCode, true
}

// SetAuthCode sets field value
func (o *DomainTransferIn) SetAuthCode(v string) {
	o.AuthCode = v
}

// GetConsent returns the Consent field value
func (o *DomainTransferIn) GetConsent() Consent {
	if o == nil  {
		var ret Consent
		return ret
	}

	return o.Consent
}

// GetConsentOk returns a tuple with the Consent field value
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetConsentOk() (*Consent, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Consent, true
}

// SetConsent sets field value
func (o *DomainTransferIn) SetConsent(v Consent) {
	o.Consent = v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *DomainTransferIn) GetPeriod() int32 {
	if o == nil || o.Period == nil {
		var ret int32
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetPeriodOk() (*int32, bool) {
	if o == nil || o.Period == nil {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *DomainTransferIn) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int32 and assigns it to the Period field.
func (o *DomainTransferIn) SetPeriod(v int32) {
	o.Period = &v
}

// GetPrivacy returns the Privacy field value if set, zero value otherwise.
func (o *DomainTransferIn) GetPrivacy() bool {
	if o == nil || o.Privacy == nil {
		var ret bool
		return ret
	}
	return *o.Privacy
}

// GetPrivacyOk returns a tuple with the Privacy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetPrivacyOk() (*bool, bool) {
	if o == nil || o.Privacy == nil {
		return nil, false
	}
	return o.Privacy, true
}

// HasPrivacy returns a boolean if a field has been set.
func (o *DomainTransferIn) HasPrivacy() bool {
	if o != nil && o.Privacy != nil {
		return true
	}

	return false
}

// SetPrivacy gets a reference to the given bool and assigns it to the Privacy field.
func (o *DomainTransferIn) SetPrivacy(v bool) {
	o.Privacy = &v
}

// GetRenewAuto returns the RenewAuto field value if set, zero value otherwise.
func (o *DomainTransferIn) GetRenewAuto() bool {
	if o == nil || o.RenewAuto == nil {
		var ret bool
		return ret
	}
	return *o.RenewAuto
}

// GetRenewAutoOk returns a tuple with the RenewAuto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetRenewAutoOk() (*bool, bool) {
	if o == nil || o.RenewAuto == nil {
		return nil, false
	}
	return o.RenewAuto, true
}

// HasRenewAuto returns a boolean if a field has been set.
func (o *DomainTransferIn) HasRenewAuto() bool {
	if o != nil && o.RenewAuto != nil {
		return true
	}

	return false
}

// SetRenewAuto gets a reference to the given bool and assigns it to the RenewAuto field.
func (o *DomainTransferIn) SetRenewAuto(v bool) {
	o.RenewAuto = &v
}

// GetContactAdmin returns the ContactAdmin field value if set, zero value otherwise.
func (o *DomainTransferIn) GetContactAdmin() Contact {
	if o == nil || o.ContactAdmin == nil {
		var ret Contact
		return ret
	}
	return *o.ContactAdmin
}

// GetContactAdminOk returns a tuple with the ContactAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetContactAdminOk() (*Contact, bool) {
	if o == nil || o.ContactAdmin == nil {
		return nil, false
	}
	return o.ContactAdmin, true
}

// HasContactAdmin returns a boolean if a field has been set.
func (o *DomainTransferIn) HasContactAdmin() bool {
	if o != nil && o.ContactAdmin != nil {
		return true
	}

	return false
}

// SetContactAdmin gets a reference to the given Contact and assigns it to the ContactAdmin field.
func (o *DomainTransferIn) SetContactAdmin(v Contact) {
	o.ContactAdmin = &v
}

// GetContactBilling returns the ContactBilling field value if set, zero value otherwise.
func (o *DomainTransferIn) GetContactBilling() Contact {
	if o == nil || o.ContactBilling == nil {
		var ret Contact
		return ret
	}
	return *o.ContactBilling
}

// GetContactBillingOk returns a tuple with the ContactBilling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetContactBillingOk() (*Contact, bool) {
	if o == nil || o.ContactBilling == nil {
		return nil, false
	}
	return o.ContactBilling, true
}

// HasContactBilling returns a boolean if a field has been set.
func (o *DomainTransferIn) HasContactBilling() bool {
	if o != nil && o.ContactBilling != nil {
		return true
	}

	return false
}

// SetContactBilling gets a reference to the given Contact and assigns it to the ContactBilling field.
func (o *DomainTransferIn) SetContactBilling(v Contact) {
	o.ContactBilling = &v
}

// GetContactRegistrant returns the ContactRegistrant field value if set, zero value otherwise.
func (o *DomainTransferIn) GetContactRegistrant() Contact {
	if o == nil || o.ContactRegistrant == nil {
		var ret Contact
		return ret
	}
	return *o.ContactRegistrant
}

// GetContactRegistrantOk returns a tuple with the ContactRegistrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetContactRegistrantOk() (*Contact, bool) {
	if o == nil || o.ContactRegistrant == nil {
		return nil, false
	}
	return o.ContactRegistrant, true
}

// HasContactRegistrant returns a boolean if a field has been set.
func (o *DomainTransferIn) HasContactRegistrant() bool {
	if o != nil && o.ContactRegistrant != nil {
		return true
	}

	return false
}

// SetContactRegistrant gets a reference to the given Contact and assigns it to the ContactRegistrant field.
func (o *DomainTransferIn) SetContactRegistrant(v Contact) {
	o.ContactRegistrant = &v
}

// GetContactTech returns the ContactTech field value if set, zero value otherwise.
func (o *DomainTransferIn) GetContactTech() Contact {
	if o == nil || o.ContactTech == nil {
		var ret Contact
		return ret
	}
	return *o.ContactTech
}

// GetContactTechOk returns a tuple with the ContactTech field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTransferIn) GetContactTechOk() (*Contact, bool) {
	if o == nil || o.ContactTech == nil {
		return nil, false
	}
	return o.ContactTech, true
}

// HasContactTech returns a boolean if a field has been set.
func (o *DomainTransferIn) HasContactTech() bool {
	if o != nil && o.ContactTech != nil {
		return true
	}

	return false
}

// SetContactTech gets a reference to the given Contact and assigns it to the ContactTech field.
func (o *DomainTransferIn) SetContactTech(v Contact) {
	o.ContactTech = &v
}

func (o DomainTransferIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["authCode"] = o.AuthCode
	}
	if true {
		toSerialize["consent"] = o.Consent
	}
	if o.Period != nil {
		toSerialize["period"] = o.Period
	}
	if o.Privacy != nil {
		toSerialize["privacy"] = o.Privacy
	}
	if o.RenewAuto != nil {
		toSerialize["renewAuto"] = o.RenewAuto
	}
	if o.ContactAdmin != nil {
		toSerialize["contactAdmin"] = o.ContactAdmin
	}
	if o.ContactBilling != nil {
		toSerialize["contactBilling"] = o.ContactBilling
	}
	if o.ContactRegistrant != nil {
		toSerialize["contactRegistrant"] = o.ContactRegistrant
	}
	if o.ContactTech != nil {
		toSerialize["contactTech"] = o.ContactTech
	}
	return json.Marshal(toSerialize)
}

type NullableDomainTransferIn struct {
	value *DomainTransferIn
	isSet bool
}

func (v NullableDomainTransferIn) Get() *DomainTransferIn {
	return v.value
}

func (v *NullableDomainTransferIn) Set(val *DomainTransferIn) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainTransferIn) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainTransferIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainTransferIn(val *DomainTransferIn) *NullableDomainTransferIn {
	return &NullableDomainTransferIn{value: val, isSet: true}
}

func (v NullableDomainTransferIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainTransferIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


