/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type DomainPurchaseResponse struct {
	// Currency in which the `total` is listed
	Currency string `json:"currency,omitempty"`
	// Number items included in the order
	ItemCount int32 `json:"itemCount"`
	// Unique identifier of the order processed to purchase the domain
	OrderId int32 `json:"orderId"`
	// Total cost of the domain and any selected add-ons
	Total int32 `json:"total"`
}
