/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type ErrorFieldDomainContactsValidate struct {
	// Short identifier for the error, suitable for indicating the specific error within client code
	Code string `json:"code"`
	// An array of domain names the error is for. If tlds are specified in the request, `domains` will contain tlds. For example, if `domains` in request is [\"test1.com\", \"test2.uk\", \"net\"], and the field is invalid for com and net, then one of the `fields` in response will have [\"test1.com\", \"net\"] as `domains`
	Domains []string `json:"domains"`
	// Human-readable, English description of the problem with the contents of the field
	Message string `json:"message,omitempty"`
	// 1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error
	Path string `json:"path"`
	// JSONPath referring to the field on the object referenced by `path` containing an error
	PathRelated string `json:"pathRelated,omitempty"`
}
