/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type LegalAgreement struct {
	// Unique identifier for the legal agreement
	AgreementKey string `json:"agreementKey"`
	// Contents of the legal agreement, suitable for embedding
	Content string `json:"content"`
	// Title of the legal agreement
	Title string `json:"title"`
	// URL to a page containing the legal agreement
	Url string `json:"url,omitempty"`
}
