/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type JsonDataType struct {
	Format string `json:"format,omitempty"`
	Pattern string `json:"pattern,omitempty"`
	Type_ string `json:"type"`
}
