/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type DomainUpdate struct {
	// Whether or not the domain should be locked to prevent transfers
	Locked bool `json:"locked,omitempty"`
	// Fully-qualified domain names for Name Servers to associate with the domain
	NameServers []string `json:"nameServers,omitempty"`
	// Whether or not the domain should be configured to automatically renew
	RenewAuto bool `json:"renewAuto,omitempty"`
	// Reseller subaccount shopperid who can manage the domain
	SubaccountId string `json:"subaccountId,omitempty"`
}
