/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type Address struct {
	Address1 string `json:"address1"`
	Address2 string `json:"address2,omitempty"`
	City string `json:"city"`
	// Two-letter ISO country code to be used as a hint for target region<br/><br/> NOTE: These are sample values, there are many <a href='http://www.iso.org/iso/country_codes.htm'>more</a>
	Country string `json:"country"`
	// Postal or zip code
	PostalCode string `json:"postalCode"`
	// State or province or territory
	State string `json:"state"`
}
