/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type DomainAvailableBulk struct {
	// Domain available response array
	Domains []DomainAvailableResponse `json:"domains"`
}
