/*
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package godaddy

import (
	"encoding/json"
)

// DNSRecordCreateTypeName struct for DNSRecordCreateTypeName
type DNSRecordCreateTypeName struct {
	Data string `json:"data"`
	// Service port (SRV only)
	Port *int32 `json:"port,omitempty"`
	// Record priority (MX and SRV only)
	Priority *int32 `json:"priority,omitempty"`
	// Service protocol (SRV only)
	Protocol *string `json:"protocol,omitempty"`
	// Service type (SRV only)
	Service *string `json:"service,omitempty"`
	Ttl *int32 `json:"ttl,omitempty"`
	// Record weight (SRV only)
	Weight *int32 `json:"weight,omitempty"`
}

// NewDNSRecordCreateTypeName instantiates a new DNSRecordCreateTypeName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDNSRecordCreateTypeName(data string, ) *DNSRecordCreateTypeName {
	this := DNSRecordCreateTypeName{}
	this.Data = data
	return &this
}

// NewDNSRecordCreateTypeNameWithDefaults instantiates a new DNSRecordCreateTypeName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDNSRecordCreateTypeNameWithDefaults() *DNSRecordCreateTypeName {
	this := DNSRecordCreateTypeName{}
	return &this
}

// GetData returns the Data field value
func (o *DNSRecordCreateTypeName) GetData() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetDataOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DNSRecordCreateTypeName) SetData(v string) {
	o.Data = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetPort() int32 {
	if o == nil || o.Port == nil {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetPortOk() (*int32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *DNSRecordCreateTypeName) SetPort(v int32) {
	o.Port = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetPriority() int32 {
	if o == nil || o.Priority == nil {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetPriorityOk() (*int32, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *DNSRecordCreateTypeName) SetPriority(v int32) {
	o.Priority = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetProtocol() string {
	if o == nil || o.Protocol == nil {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetProtocolOk() (*string, bool) {
	if o == nil || o.Protocol == nil {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasProtocol() bool {
	if o != nil && o.Protocol != nil {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *DNSRecordCreateTypeName) SetProtocol(v string) {
	o.Protocol = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetServiceOk() (*string, bool) {
	if o == nil || o.Service == nil {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *DNSRecordCreateTypeName) SetService(v string) {
	o.Service = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetTtl() int32 {
	if o == nil || o.Ttl == nil {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetTtlOk() (*int32, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *DNSRecordCreateTypeName) SetTtl(v int32) {
	o.Ttl = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *DNSRecordCreateTypeName) GetWeight() int32 {
	if o == nil || o.Weight == nil {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordCreateTypeName) GetWeightOk() (*int32, bool) {
	if o == nil || o.Weight == nil {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *DNSRecordCreateTypeName) HasWeight() bool {
	if o != nil && o.Weight != nil {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *DNSRecordCreateTypeName) SetWeight(v int32) {
	o.Weight = &v
}

func (o DNSRecordCreateTypeName) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.Protocol != nil {
		toSerialize["protocol"] = o.Protocol
	}
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	if o.Weight != nil {
		toSerialize["weight"] = o.Weight
	}
	return json.Marshal(toSerialize)
}

type NullableDNSRecordCreateTypeName struct {
	value *DNSRecordCreateTypeName
	isSet bool
}

func (v NullableDNSRecordCreateTypeName) Get() *DNSRecordCreateTypeName {
	return v.value
}

func (v *NullableDNSRecordCreateTypeName) Set(val *DNSRecordCreateTypeName) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSRecordCreateTypeName) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSRecordCreateTypeName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSRecordCreateTypeName(val *DNSRecordCreateTypeName) *NullableDNSRecordCreateTypeName {
	return &NullableDNSRecordCreateTypeName{value: val, isSet: true}
}

func (v NullableDNSRecordCreateTypeName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSRecordCreateTypeName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


