/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type VerificationsDomain struct {
	// Verification of domain name against a prohibited list maintained by the government
	DomainName *VerificationDomainName `json:"domainName,omitempty"`
	// Verification of identity by comparing registration data against government issued documents
	RealName *VerificationRealName `json:"realName,omitempty"`
}
