/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package godaddy

type TldSummary struct {
	// Name of the top-level domain
	Name string `json:"name"`
	// Type of the top-level domain
	Type_ string `json:"type"`
}
